ArithmeticError 
AssertionError 	
AttributeError 
Exception 	
EOFError 	
FloatingPointError 
GeneratorExit 	
ImportError 	
IndentationError 	
IndexError 	
KeyError 	
KeyboardInterrupt 	
LookupError 	
MemoryError 	
NameError 	
NotImplementedError 	
OSError 	
OverflowError 	
ReferenceError 	
RuntimeError 	
StopIteration 	
SyntaxError 	
TabError 	
SystemError 	
SystemExit 	
TypeError 	
UnboundLocalError 	
UnicodeError 	
UnicodeEncodeError 	
UnicodeDecodeError 	
UnicodeTranslateError 	
ValueError 
ZeroDivisionError 
